
static const std::vector<Vertex> cube_verts = {
    // Front Face (Z+)
    {.position = {-0.5, -0.5, 0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({0, 0, 1}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, -0.5, 0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({0, 0, 1}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, 0.5, 0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({0, 0, 1}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, 0.5, 0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({0, 0, 1}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    // Back Face (Z-)
    {.position = {0.5, -0.5, -0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({0, 0, -1}),
     .tangent = pack_normal({-1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, -0.5, -0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({0, 0, -1}),
     .tangent = pack_normal({-1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, 0.5, -0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({0, 0, -1}),
     .tangent = pack_normal({-1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, 0.5, -0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({0, 0, -1}),
     .tangent = pack_normal({-1, 0, 0}),
     .bitangent = pack_normal({0, 1, 0})},
    // Left Face (X-)
    {.position = {-0.5, -0.5, -0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({-1, 0, 0}),
     .tangent = pack_normal({0, 0, 1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, -0.5, 0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({-1, 0, 0}),
     .tangent = pack_normal({0, 0, 1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, 0.5, 0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({-1, 0, 0}),
     .tangent = pack_normal({0, 0, 1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {-0.5, 0.5, -0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({-1, 0, 0}),
     .tangent = pack_normal({0, 0, 1}),
     .bitangent = pack_normal({0, 1, 0})},
    // Right Face (X+)
    {.position = {0.5, -0.5, 0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({1, 0, 0}),
     .tangent = pack_normal({0, 0, -1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, -0.5, -0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({1, 0, 0}),
     .tangent = pack_normal({0, 0, -1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, 0.5, -0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({1, 0, 0}),
     .tangent = pack_normal({0, 0, -1}),
     .bitangent = pack_normal({0, 1, 0})},
    {.position = {0.5, 0.5, 0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({1, 0, 0}),
     .tangent = pack_normal({0, 0, -1}),
     .bitangent = pack_normal({0, 1, 0})},
    // Top Face (Y+)
    {.position = {-0.5, 0.5, 0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({0, 1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, -1})},
    {.position = {0.5, 0.5, 0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({0, 1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, -1})},
    {.position = {0.5, 0.5, -0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({0, 1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, -1})},
    {.position = {-0.5, 0.5, -0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({0, 1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, -1})},
    // Bottom Face (Y-)
    {.position = {-0.5, -0.5, -0.5},
     .uvs = pack_uv({0, 0}),
     .uvs1 = pack_uv({0, 0}),
     .normal = pack_normal({0, -1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, 1})},
    {.position = {0.5, -0.5, -0.5},
     .uvs = pack_uv({1, 0}),
     .uvs1 = pack_uv({1, 0}),
     .normal = pack_normal({0, -1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, 1})},
    {.position = {0.5, -0.5, 0.5},
     .uvs = pack_uv({1, 1}),
     .uvs1 = pack_uv({1, 1}),
     .normal = pack_normal({0, -1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, 1})},
    {.position = {-0.5, -0.5, 0.5},
     .uvs = pack_uv({0, 1}),
     .uvs1 = pack_uv({0, 1}),
     .normal = pack_normal({0, -1, 0}),
     .tangent = pack_normal({1, 0, 0}),
     .bitangent = pack_normal({0, 0, 1})},
};

static const std::vector<uint32_t> cube_indices = {
    0,  1,  2,  2,  3,  0,  // Front
    4,  5,  6,  6,  7,  4,  // Back
    8,  9,  10, 10, 11, 8,  // Left
    12, 13, 14, 14, 15, 12, // Right
    16, 17, 18, 18, 19, 16, // Top
    20, 21, 22, 22, 23, 20, // Bottom
};
